FROM node:22-alpine

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

ENV GMAIL_USER="shubhamkarmarathe2@gmail.com"
ENV GMAIL_PASS="qyps apyr zwhb gafd"
ENV PORT=3002
ENV NODE_ENV="production"

EXPOSE 3002

CMD [ "npx","nodemon","index.ts" ]
